/** Only UI-owned labels are translated. Never rewrite user conversations, names or metadata. */
export const SPANISH_LABELS: Record<string, string> = {
  General: "General",
  Import: "Importar",
  Profile: "Perfil",
  Appearance: "Apariencia",
  Voice: "Voz",
  Configuration: "Configuración",
  Personalization: "Personalización",
  Pets: "Mascotas",
  "Keyboard shortcuts": "Atajos de teclado",
  "Usage & billing": "Uso y facturación",
  Analytics: "Estadísticas",
  Account: "Cuenta",
  "Computer use": "Uso del ordenador",
  "Computer history": "Historial del ordenador",
  Appshots: "Capturas",
  Plugins: "Complementos",
  Browser: "Navegador",
  Hooks: "Automatizaciones",
  Connections: "Conexiones",
  Git: "Git",
  Environments: "Entornos",
  Worktrees: "Espacios de trabajo",
  "Archived chats": "Chats archivados",
  Personal: "Personal",
  Integrations: "Integraciones",
  Coding: "Avanzado",
  Archived: "Archivado",
  "Back to app": "Volver a la aplicación",
  Settings: "Ajustes",
  "Search settings…": "Buscar ajustes…",
  "New chat": "Nuevo chat",
  Shoots: "Sesiones",
  "New Shoot": "Nueva sesión",
  "Archived Shoots": "Sesiones archivadas",
  "Recent Shoots": "Sesiones recientes",
  "Show Recent Shoots": "Mostrar sesiones recientes",
  "Show Archived Shoots": "Mostrar sesiones archivadas",
  "Share with Client…": "Compartir con cliente…",
  "Restore Shoot": "Restaurar sesión",
  "Delete Shoot…": "Eliminar sesión…",
  "New Section…": "Nueva sección…",
  "Open in Side Panel": "Abrir en panel lateral",
  "Mark as Read": "Marcar como leído",
  "Mark as Unread": "Marcar como no leído",
  "Adobe Export…": "Exportar a Adobe…",
  "All Tools": "Todas las herramientas",
  Chat: "Chat",
  Studio: "Estudio",
  Delivery: "Entrega",
  Clients: "Clientes",
  "All tools": "Todas las herramientas",
  "Photo assistant": "Asistente de fotografía",
  "Conversations in this shoot": "Conversaciones de esta sesión",
  "Chats in this shoot": "Chats de esta sesión",
  Pinned: "Fijados",
  "Recent chats": "Chats recientes",
  "Share with client…": "Compartir con cliente…",
  Rename: "Renombrar",
  Pin: "Fijar",
  Unpin: "Desfijar",
  Archive: "Archivar",
  "Restore chat": "Restaurar chat",
  "Delete chat…": "Eliminar chat…",
  Section: "Sección",
  "New section…": "Nueva sección…",
  "Open in Quick Chat": "Abrir en chat rápido",
  "Mark as read": "Marcar como leído",
  "Mark as unread": "Marcar como no leído",
  "Adobe export…": "Exportar a Adobe…",
  Permissions: "Permisos",
  "Default permissions": "Permisos predeterminados",
  "Full access": "Acceso completo",
  "Projectless task folder": "Carpeta sin proyecto",
  "Default file open destination": "Destino predeterminado de archivos",
  Language: "Idioma",
  Contrast: "Contraste",
  "Accent color": "Color de acento",
  "Custom accent": "Acento personalizado",
  "Accent style": "Estilo de acento",
  "Gradient end": "Fin del degradado",
  "Workspace grid": "Cuadrícula",
  System: "Sistema",
  Standard: "Estándar",
  More: "Más",
  Default: "Predeterminado",
  Dark: "Oscuro",
  Light: "Claro",
  Solid: "Sólido",
  Gradient: "Degradado",
  Custom: "Personalizado",
  Blue: "Azul",
  Green: "Verde",
  Yellow: "Amarillo",
  Pink: "Rosa",
  Orange: "Naranja",
  Purple: "Morado",
  White: "Blanco",
  Theme: "Tema",
  "Dark theme": "Tema oscuro",
  Background: "Fondo",
  Foreground: "Texto",
  "UI font": "Fuente de interfaz",
  "Code font": "Fuente de código",
  "Interface size": "Tamaño de interfaz",
  "Code size": "Tamaño de código",
  Density: "Densidad",
  Compact: "Compacta",
  Comfortable: "Cómoda",
  "Translucent sidebar": "Barra lateral translúcida",
  "Text contrast": "Contraste de texto",
  Preferences: "Preferencias",
  "Reduce motion": "Reducir movimiento",
  "Use pointer cursors": "Usar cursores de enlace",
  "Keep sidebar open": "Mantener barra lateral abierta",
  "Prevent sleep while running": "Evitar suspensión durante tareas",
  "Completion notifications": "Notificaciones de finalización",
  "Desktop notifications": "Notificaciones de escritorio",
  Notifications: "Notificaciones",
  Save: "Guardar",
  Cancel: "Cancelar",
};
export function workspaceLanguage(value: "en" | "es" | "auto", browserLanguage = "en") {
  return value === "auto" ? (browserLanguage.toLowerCase().startsWith("es") ? "es" : "en") : value;
}
export function workspaceText(text: string, language: "en" | "es") {
  return language === "es" ? (SPANISH_LABELS[text] ?? text) : text;
}
