import { expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { renderToStaticMarkup } from "react-dom/server";
import { BrandMark } from "../src/components/marketing/BrandMark";

test("connector marks use official X and Snapchat paths, not fat stand-ins", () => {
  const x = renderToStaticMarkup(<BrandMark id="x" />);
  expect(x).toContain("M14.234 10.162");
  const snap = renderToStaticMarkup(<BrandMark id="snapchat" />);
  expect(snap).toContain("M12.206.793");
  expect(snap).toContain("#FFFC00");
  const threads = renderToStaticMarkup(<BrandMark id="threads" />);
  expect(threads).toContain("M12.186 24");
  const lightroom = renderToStaticMarkup(<BrandMark id="lightroom" />);
  expect(lightroom).toContain("M52.5223 0H11.4777");
  expect(lightroom).toContain("#001E36");
  expect(lightroom).toContain("#31A8FF");
  expect(lightroom).not.toContain("M19.75.3H4.25C1.9.3 0 2.2 0 4.55v14.9");
  const photoshop = renderToStaticMarkup(<BrandMark id="photoshop" />);
  expect(photoshop).toContain("M34.4678 0H7.53225");
  expect(photoshop).toContain("#001E36");
  const tiktok = renderToStaticMarkup(<BrandMark id="tiktok" />);
  expect(tiktok).toContain("#25F4EE");
  expect(tiktok).toContain("#FE2C55");
  const instagram = renderToStaticMarkup(<BrandMark id="instagram" />);
  expect(instagram).toContain("brand-ig-fill");
  expect(instagram).toContain("#d6249f");
  expect(instagram).not.toContain("#E4405F");
  expect(instagram).not.toContain("M7.0301.084");
  expect(renderToStaticMarkup(<BrandMark id="pinterest" />)).toContain("#E60023");
  expect(renderToStaticMarkup(<BrandMark id="facebook" />)).toContain("#1877F2");
  const shorts = renderToStaticMarkup(<BrandMark id="youtube-shorts" />);
  expect(shorts).toContain("m18.931 9.99");
  expect(shorts).toContain("#FF0000");
  expect(shorts).not.toContain("M18.24 2.1");
  const gbp = renderToStaticMarkup(<BrandMark id="google-business" />);
  expect(gbp).toContain("M3.273 1.636");
  expect(gbp).toContain("#4285F4");
  expect(gbp).toContain("#EA4335");
  expect(gbp).toContain("#FBBC04");
  expect(gbp).toContain("#34A853");
  expect(gbp).not.toContain("M4.4 10.2");
  expect(renderToStaticMarkup(<BrandMark id="discord" />)).toContain("#5865F2");
  const mastodon = renderToStaticMarkup(<BrandMark id="mastodon" />);
  expect(mastodon).toContain("M23.268 5.313");
  expect(mastodon).toContain("#6364FF");
  const woo = renderToStaticMarkup(<BrandMark id="woocommerce" />);
  expect(woo).toContain("M.754 9.58");
  expect(woo).toContain("#96588A");
  expect(renderToStaticMarkup(<BrandMark id="dribbble" />)).toContain("#EA4C89");
  expect(renderToStaticMarkup(<BrandMark id="kick" />)).toContain("#53FC18");
  expect(renderToStaticMarkup(<BrandMark id="twitch" />)).toContain("#9146FF");
  expect(renderToStaticMarkup(<BrandMark id="chatgpt" />)).toContain("M22.282 9.821");
  expect(renderToStaticMarkup(<BrandMark id="gemini" />)).toContain("#8E75B2");
  expect(renderToStaticMarkup(<BrandMark id="n8n" />)).toContain("#EA4B71");
  const source = readFileSync(new URL("../src/lib/connector-orbit.ts", import.meta.url), "utf8");
  expect(source).toContain("0.12");
});
