/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdobeRouteImport } from './routes/adobe'
import { Route as AmbassadorRouteImport } from './routes/ambassador'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookRouteImport } from './routes/book'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as DeliverRouteImport } from './routes/deliver'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as MetadataRouteImport } from './routes/metadata'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as PickRouteImport } from './routes/pick'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as SendRouteImport } from './routes/send'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShootRouteImport } from './routes/shoot'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as GSlugRouteImport } from './routes/g.$slug'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as ApiPublicLightroomRouteImport } from './routes/api/public/lightroom'
import { Route as ApiPublicStripeConnectCallbackRouteImport } from './routes/api/public/stripe/connect-callback'
import { Route as ApiPublicStripeConnectWebhookRouteImport } from './routes/api/public/stripe/connect-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdobeRoute = AdobeRouteImport.update({
  id: '/adobe',
  path: '/adobe',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbassadorRoute = AmbassadorRouteImport.update({
  id: '/ambassador',
  path: '/ambassador',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliverRoute = DeliverRouteImport.update({
  id: '/deliver',
  path: '/deliver',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const MetadataRoute = MetadataRouteImport.update({
  id: '/metadata',
  path: '/metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const PickRoute = PickRouteImport.update({
  id: '/pick',
  path: '/pick',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesRoute = RatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShootRoute = ShootRouteImport.update({
  id: '/shoot',
  path: '/shoot',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const GSlugRoute = GSlugRouteImport.update({
  id: '/g/$slug',
  path: '/g/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLightroomRoute = ApiPublicLightroomRouteImport.update({
  id: '/api/public/lightroom',
  path: '/api/public/lightroom',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeConnectCallbackRoute =
  ApiPublicStripeConnectCallbackRouteImport.update({
    id: '/api/public/stripe/connect-callback',
    path: '/api/public/stripe/connect-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStripeConnectWebhookRoute =
  ApiPublicStripeConnectWebhookRouteImport.update({
    id: '/api/public/stripe/connect-webhook',
    path: '/api/public/stripe/connect-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adobe': typeof AdobeRoute
  '/ambassador': typeof AmbassadorRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/business': typeof BusinessRoute
  '/clients': typeof ClientsRoute
  '/community': typeof CommunityRoute
  '/deliver': typeof DeliverRoute
  '/desk': typeof DeskRoute
  '/earnings': typeof EarningsRoute
  '/metadata': typeof MetadataRoute
  '/packages': typeof PackagesRoute
  '/pick': typeof PickRoute
  '/portal': typeof PortalRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/rates': typeof RatesRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/shoot': typeof ShootRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRoute
  '/api/chat': typeof ApiChatRoute
  '/g/$slug': typeof GSlugRoute
  '/s/$token': typeof STokenRoute
  '/api/public/lightroom': typeof ApiPublicLightroomRoute
  '/api/public/stripe/connect-callback': typeof ApiPublicStripeConnectCallbackRoute
  '/api/public/stripe/connect-webhook': typeof ApiPublicStripeConnectWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adobe': typeof AdobeRoute
  '/ambassador': typeof AmbassadorRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/business': typeof BusinessRoute
  '/clients': typeof ClientsRoute
  '/community': typeof CommunityRoute
  '/deliver': typeof DeliverRoute
  '/desk': typeof DeskRoute
  '/earnings': typeof EarningsRoute
  '/metadata': typeof MetadataRoute
  '/packages': typeof PackagesRoute
  '/pick': typeof PickRoute
  '/portal': typeof PortalRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/rates': typeof RatesRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/shoot': typeof ShootRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRoute
  '/api/chat': typeof ApiChatRoute
  '/g/$slug': typeof GSlugRoute
  '/s/$token': typeof STokenRoute
  '/api/public/lightroom': typeof ApiPublicLightroomRoute
  '/api/public/stripe/connect-callback': typeof ApiPublicStripeConnectCallbackRoute
  '/api/public/stripe/connect-webhook': typeof ApiPublicStripeConnectWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adobe': typeof AdobeRoute
  '/ambassador': typeof AmbassadorRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/business': typeof BusinessRoute
  '/clients': typeof ClientsRoute
  '/community': typeof CommunityRoute
  '/deliver': typeof DeliverRoute
  '/desk': typeof DeskRoute
  '/earnings': typeof EarningsRoute
  '/metadata': typeof MetadataRoute
  '/packages': typeof PackagesRoute
  '/pick': typeof PickRoute
  '/portal': typeof PortalRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/rates': typeof RatesRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/shoot': typeof ShootRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRoute
  '/api/chat': typeof ApiChatRoute
  '/g/$slug': typeof GSlugRoute
  '/s/$token': typeof STokenRoute
  '/api/public/lightroom': typeof ApiPublicLightroomRoute
  '/api/public/stripe/connect-callback': typeof ApiPublicStripeConnectCallbackRoute
  '/api/public/stripe/connect-webhook': typeof ApiPublicStripeConnectWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adobe'
    | '/ambassador'
    | '/auth'
    | '/book'
    | '/business'
    | '/clients'
    | '/community'
    | '/deliver'
    | '/desk'
    | '/earnings'
    | '/metadata'
    | '/packages'
    | '/pick'
    | '/portal'
    | '/portfolio'
    | '/pricing'
    | '/rates'
    | '/send'
    | '/settings'
    | '/shoot'
    | '/signup'
    | '/studio'
    | '/api/chat'
    | '/g/$slug'
    | '/s/$token'
    | '/api/public/lightroom'
    | '/api/public/stripe/connect-callback'
    | '/api/public/stripe/connect-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adobe'
    | '/ambassador'
    | '/auth'
    | '/book'
    | '/business'
    | '/clients'
    | '/community'
    | '/deliver'
    | '/desk'
    | '/earnings'
    | '/metadata'
    | '/packages'
    | '/pick'
    | '/portal'
    | '/portfolio'
    | '/pricing'
    | '/rates'
    | '/send'
    | '/settings'
    | '/shoot'
    | '/signup'
    | '/studio'
    | '/api/chat'
    | '/g/$slug'
    | '/s/$token'
    | '/api/public/lightroom'
    | '/api/public/stripe/connect-callback'
    | '/api/public/stripe/connect-webhook'
  id:
    | '__root__'
    | '/'
    | '/adobe'
    | '/ambassador'
    | '/auth'
    | '/book'
    | '/business'
    | '/clients'
    | '/community'
    | '/deliver'
    | '/desk'
    | '/earnings'
    | '/metadata'
    | '/packages'
    | '/pick'
    | '/portal'
    | '/portfolio'
    | '/pricing'
    | '/rates'
    | '/send'
    | '/settings'
    | '/shoot'
    | '/signup'
    | '/studio'
    | '/api/chat'
    | '/g/$slug'
    | '/s/$token'
    | '/api/public/lightroom'
    | '/api/public/stripe/connect-callback'
    | '/api/public/stripe/connect-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdobeRoute: typeof AdobeRoute
  AmbassadorRoute: typeof AmbassadorRoute
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  BusinessRoute: typeof BusinessRoute
  ClientsRoute: typeof ClientsRoute
  CommunityRoute: typeof CommunityRoute
  DeliverRoute: typeof DeliverRoute
  DeskRoute: typeof DeskRoute
  EarningsRoute: typeof EarningsRoute
  MetadataRoute: typeof MetadataRoute
  PackagesRoute: typeof PackagesRoute
  PickRoute: typeof PickRoute
  PortalRoute: typeof PortalRoute
  PortfolioRoute: typeof PortfolioRoute
  PricingRoute: typeof PricingRoute
  RatesRoute: typeof RatesRoute
  SendRoute: typeof SendRoute
  SettingsRoute: typeof SettingsRoute
  ShootRoute: typeof ShootRoute
  SignupRoute: typeof SignupRoute
  StudioRoute: typeof StudioRoute
  ApiChatRoute: typeof ApiChatRoute
  GSlugRoute: typeof GSlugRoute
  STokenRoute: typeof STokenRoute
  ApiPublicLightroomRoute: typeof ApiPublicLightroomRoute
  ApiPublicStripeConnectCallbackRoute: typeof ApiPublicStripeConnectCallbackRoute
  ApiPublicStripeConnectWebhookRoute: typeof ApiPublicStripeConnectWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adobe': {
      id: '/adobe'
      path: '/adobe'
      fullPath: '/adobe'
      preLoaderRoute: typeof AdobeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambassador': {
      id: '/ambassador'
      path: '/ambassador'
      fullPath: '/ambassador'
      preLoaderRoute: typeof AmbassadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliver': {
      id: '/deliver'
      path: '/deliver'
      fullPath: '/deliver'
      preLoaderRoute: typeof DeliverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metadata': {
      id: '/metadata'
      path: '/metadata'
      fullPath: '/metadata'
      preLoaderRoute: typeof MetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pick': {
      id: '/pick'
      path: '/pick'
      fullPath: '/pick'
      preLoaderRoute: typeof PickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates': {
      id: '/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoot': {
      id: '/shoot'
      path: '/shoot'
      fullPath: '/shoot'
      preLoaderRoute: typeof ShootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$slug': {
      id: '/g/$slug'
      path: '/g/$slug'
      fullPath: '/g/$slug'
      preLoaderRoute: typeof GSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lightroom': {
      id: '/api/public/lightroom'
      path: '/api/public/lightroom'
      fullPath: '/api/public/lightroom'
      preLoaderRoute: typeof ApiPublicLightroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe/connect-callback': {
      id: '/api/public/stripe/connect-callback'
      path: '/api/public/stripe/connect-callback'
      fullPath: '/api/public/stripe/connect-callback'
      preLoaderRoute: typeof ApiPublicStripeConnectCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe/connect-webhook': {
      id: '/api/public/stripe/connect-webhook'
      path: '/api/public/stripe/connect-webhook'
      fullPath: '/api/public/stripe/connect-webhook'
      preLoaderRoute: typeof ApiPublicStripeConnectWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdobeRoute: AdobeRoute,
  AmbassadorRoute: AmbassadorRoute,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  BusinessRoute: BusinessRoute,
  ClientsRoute: ClientsRoute,
  CommunityRoute: CommunityRoute,
  DeliverRoute: DeliverRoute,
  DeskRoute: DeskRoute,
  EarningsRoute: EarningsRoute,
  MetadataRoute: MetadataRoute,
  PackagesRoute: PackagesRoute,
  PickRoute: PickRoute,
  PortalRoute: PortalRoute,
  PortfolioRoute: PortfolioRoute,
  PricingRoute: PricingRoute,
  RatesRoute: RatesRoute,
  SendRoute: SendRoute,
  SettingsRoute: SettingsRoute,
  ShootRoute: ShootRoute,
  SignupRoute: SignupRoute,
  StudioRoute: StudioRoute,
  ApiChatRoute: ApiChatRoute,
  GSlugRoute: GSlugRoute,
  STokenRoute: STokenRoute,
  ApiPublicLightroomRoute: ApiPublicLightroomRoute,
  ApiPublicStripeConnectCallbackRoute: ApiPublicStripeConnectCallbackRoute,
  ApiPublicStripeConnectWebhookRoute: ApiPublicStripeConnectWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
